apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo
  namespace: argocd
spec:
  destination:
    namespace: argo-demo
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/andrecchia/argocd-test.git
    path: .
  project: default
